### ISSUE TITLE
more spillover from stricttraits recipe modules

### ISSUE THREAD

**Issue by barentine** [bewersdorflab/nep-fitting#17]
Similar to #15 , need to find workarounds / configure traits differently: 
```
Traceback (most recent call last):
  File "c:\userfiles\andrew\code\nep-fitting\nep_fitting\dsviewer_modules\sted_psf_fitting.py", line 210, in <lambda>
    ensemble_test_btn.Bind(wx.EVT_BUTTON, lambda e: self._on_ensemble_test())
  File "c:\userfiles\andrew\code\nep-fitting\nep_fitting\dsviewer_modules\sted_psf_fitting.py", line 381, in _on_ensemble_test
    hold_ensemble_parameter_constant=False, outputName='output'))
  File "c:\userfiles\andrew\code\python-microscopy\PYME\recipes\base.py", line 166, in __init__
    self.trait_set(trait_change_notify=False, **kwargs) #don't notify here - next set will do notification.
  File "C:\Users\aesb\Miniconda3\envs\pymedev\lib\site-packages\traits\has_traits.py", line 1429, in trait_set
    setattr(self, name, value)
traits.trait_errors.TraitError: Cannot set the undefined 'hold_ensemble_parameter_constant' attribute of a 'TestEnsembleParameters' object.
Traceback (most recent call last):
  File "c:\userfiles\andrew\code\nep-fitting\nep_fitting\dsviewer_modules\sted_psf_fitting.py", line 206, in <lambda>
    ensemble_btn.Bind(wx.EVT_BUTTON, lambda e: self._on_ensemble_fit())
  File "c:\userfiles\andrew\code\nep-fitting\nep_fitting\dsviewer_modules\sted_psf_fitting.py", line 317, in _on_ensemble_fit
    hold_ensemble_parameter_constant=False, outputName='output', outputFitter='fitter')
  File "c:\userfiles\andrew\code\python-microscopy\PYME\recipes\base.py", line 166, in __init__
    self.trait_set(trait_change_notify=False, **kwargs) #don't notify here - next set will do notification.
  File "C:\Users\aesb\Miniconda3\envs\pymedev\lib\site-packages\traits\has_traits.py", line 1429, in trait_set
    setattr(self, name, value)
traits.trait_errors.TraitError: Cannot set the undefined 'outputFitter' attribute of a 'EnsembleFitProfiles' object.
```

**Comment by barentine** [comment]
closed with #18
